name: Weather API CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: '3.9'
  FLASK_ENV: 'test'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r api/Requirements.txt
        pip install pytest pytest-cov locust

    - name: Run unit tests with coverage
      run: |
        cd api
        pytest test.api_endpoints.py --cov=. --cov-report=xml
      env:
        OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}

    - name: Run performance tests
      run: |
        cd api
        locust -f test_performance.py --headless -u 50 -r 10 --run-time 1m --host=http://localhost:5000

    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      if: success()

    - name: Notify via Gmail
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.GMAIL_USERNAME }}
        password: ${{ secrets.GMAIL_APP_PASSWORD }}
        subject: "CI ${{ job.status }}: Weather API (Branch: ${{ github.ref_name }})"
        to: ${{ secrets.NOTIFICATION_EMAIL }}
        html_body: |
          <h2 style="color: ${{ job.status == 'success' ? '#2ecc71' : '#e74c3c' }};">
            Weather API CI: ${{ job.status == 'success' ? '✅ PASSED' : '❌ FAILED' }}
          </h2>
          
          <p><strong>📌 Repository:</strong> ${{ github.repository }}</p>
          <p><strong>🔗 Workflow Run:</strong> <a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">View Details</a></p>
          <p><strong>🌿 Branch:</strong> ${{ github.ref_name }}</p>
          <p><strong>🧑‍💻 Triggered by:</strong> ${{ github.actor }}</p>
          
          {{ if github.event_name == 'pull_request' }}
          <p><strong>🔀 Pull Request:</strong> #${{ github.event.pull_request.number }}</p>
          {{ else }}
          <p><strong>💾 Commit:</strong> <code>${{ github.sha }}</code></p>
          {{ endif }}
          
          <h3>Test Coverage</h3>
          <p><a href="https://codecov.io/gh/${{ github.repository }}/commit/${{ github.sha }}">View Coverage Report</a></p>