name: Weather API CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: '3.9'
  FLASK_ENV: 'test'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r api/Requirements.txt
        pip install pytest pytest-cov locust

    - name: Run unit tests with coverage
      id: unit_tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE
        cd api
        python -m pytest test_api_endpoints.py --cov=. --cov-report=xml
      env:
        OPENWEATHERMAP_API_KEY: "test_key" 

    # - name: Run performance tests
      # id: performance_tests
      # run: |
        # export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE
        # cd api
        # locust -f test_performance.py --headless -u 50 -r 10 --run-time 1m --host=http://localhost:5000

    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      if: success()

    - name: Notify via Org Email
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.mastechdigital.com
        server_port: 465
        secure: true
        username: ${{ secrets.SMTP_USERNAME  }}
        password: ${{ secrets.SMTP_PASSWORD  }}
        subject: "CI ${{ job.status }}: Weather API"
        from: "GitHub Actions <${{ secrets.SMTP_USERNAME }}>"
        to: ${{ secrets.NOTIFICATION_EMAIL }}        
        ignore_cert: false
        body: |
          Weather API CI Pipeline Results
          ==============================
          
          Status: ${{ job.status }}
          Workflow: ${{ github.workflow }}
          Run Number: ${{ github.run_number }}
          
          Details:
          - Repository: ${{ github.repository }}
          - Branch: ${{ github.ref_name }}
          - Triggered by: ${{ github.actor }}
          - Run URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          
          Test Results:
          - Unit tests: ${{ steps.unit_tests.outcome }}
          - Performance tests: ${{ steps.performance_tests.outcome }}
          
          View complete logs for details.